### PR TITLE
WIP: Add safe-updates for client

### PR DESCRIPTION
**Pull request by pasuder**
That change introduces option safe-updates for mysql clients by setting it in `~/.my.cnf`.

### CODE REVIEW

**Comment by pasuder** [comment]
WIP: Adding possibility to set it via option.

**Comment by pasuder** [comment]
How is that possible? 

https://travis-ci.org/puppetlabs/puppetlabs-mysql/jobs/383056902 - not failing
https://travis-ci.org/puppetlabs/puppetlabs-mysql/jobs/384698082 - failing

I did not modify {{spec/functions/mysql_deepmerge_spec.rb}}. It seems to be not modified for last 4 months

**Comment by pasuder** [comment]
Rebase done with commit from branch `pasuder:fix_syntax_issues`.

**Comment by david22swan** [comment]
@pasuder Your PR is currently failing acceptance tests. In addition it needs to be rebased.

**Comment by pasuder** [comment]
Woops, it is closed. I forgot..

**Comment by pasuder** [comment]
Ah, rebase should I do, I will.

**Comment by pasuder** [comment]
I will be not able to test it. Let's close it.

**Pull request closed without merging**
