### PR TITLE
Darwin OS family support

### PR DESCRIPTION
**Pull request by albac**
This is my first attempt to add support for Mac using homebrew.
I have tested this with the server.pp example successfully, but I might need to add more tests.
If anyone interested on this I can keep working on improving the support to Darwin Os family.

### CODE REVIEW

**Comment by lionce** [comment]
Hello @albac, 

Thank you for your contribution.
This new feature contains  many changes that will affect the existing functionality. 
Here are a few ideas that we suggest to be able to get this functionality added to the module:

- in the current changes you are using thekevjames/homebrew. We would not like our users to be constrained by this puppet module, since it is not an officially supported module.
- The listed operating systems in the metadata file are officially tested and maintained by puppet, as for now we are not officially supporting Darwin OS 
- We gladly accept extended feature parity across various operating systems , however it is imperative for us to ensure that any and all changes do not affect the currently supported functionality. 

Thank you very much for your patience and understanding. 
I hope this feedback makes sense for you too! 

Cheers!

**Comment by david22swan** [comment]
@albac Just checking to see if this PR was still something that you wished to pursue?

**Comment by david22swan** [comment]
@albac Apologies for the bother but I was wondering if you intended to do any further work on this pr?

**Comment by lionce** [comment]
Hello @albac ,

Please let us know if you're still working on this PR and if you need help. Thanks! 

Cheers!

**Comment by carabasdaniel** [comment]
Hello @albac,

In oder to get this PR merged, the custom facts should be moved to the dependent homebrew module and please remove Darwin from the metadata.json as we do not plan to commercially support Darwin.

**Comment by david22swan** [comment]
@albac Apologies, but due to the amount of time that pr has been left to lie fallow and your lack of response when prompted we feel that we should now close it. We regret any inconvenience that this causes you and would welcome the opportunity to review any further work that you choose to submit to our modules.
Best Wishes

**Pull request closed without merging**
