### PR TITLE
MODULES-3601 Move binary logging configuration to take place after pa…

### PR DESCRIPTION
**Pull request by QuentinMoss**
…ckage install

https://tickets.puppetlabs.com/browse/MODULES-3601

### CODE REVIEW

**Comment by QuentinMoss** [comment]
@hunner Sorry for closing the previous PR. Shortly after I thought I would give this a try. Let me know what you think.

**Comment by eborned** [comment]
Wouldn't this still result in errors when the binary log directory is unavailable during setup? The installation of the mysql-server package normally auto-starts the server. The config file has been setup to work with the log-bin directory, but that directory is created after the service has been started.

**Comment by QuentinMoss** [comment]
@eborned Here is a test deployment on CentOS 7 with binary log options defined:

https://gist.github.com/QuentinMoss/14f560dfc7cac76282639a66462f0392

**Comment by hunner** [comment]
I think just installing the package on debian/ubuntu auto-starts the service, but this will at least fix the currrent issue and allow it to work on redhat.

**Comment by bwitt** [comment]
Yes installing the package on ubuntu auto-starts the service, which results in a failure.

**Pull request merged**
