### PR TITLE
Allow the compressing of xtrabackup

### PR DESCRIPTION
**Pull request by TNAJanssen**

### CODE REVIEW

**Comment by david22swan** [comment]
@TNAJanssen Is there any movement on this?

**Comment by TNAJanssen** [comment]
Sorry, i will try to do it tomorrow!

**Comment by Lavinia-Dan** [comment]
Hello @TNAJanssen , How is it going? It looks like this PR needs some tests and docs, do you need any help with that?

**Comment by Spuffnduff** [comment]
If @TNAJanssen isn't able to help with this, I would be happy to fork from here and make an updated PR as this is something I want for work.

**Comment by sheenaajay** [comment]
Thanks @TNAJanssen . Hi @Spuffnduff ,Please let us know if you need any help.Thanks for submitting the PR.

**Comment by david22swan** [comment]
@TNAJanssen Apologies, but is there any movement on this pr?

**Comment by david22swan** [comment]
@TNAJanssen Apologies but due to the length o time this PR has been left to lie fallow and your lack of response when pinged o it we feel that it should now be closed.
We offer are apologies if this is an inconvenience to you and look forward to any future contributions that you may choose to make.

**Pull request closed without merging**
