### PR TITLE
flush privileges after user update

### PR DESCRIPTION
**Pull request by stefan-ahrefs**

### CODE REVIEW

**Comment by stefan-ahrefs** [comment]
ping

**Comment by stefan-ahrefs** [comment]
ping

**Comment by stefan-ahrefs** [comment]
ping

**Comment by stefan-ahrefs** [comment]
ping

**Comment by LukasAud** [comment]
Hi @stefan-ahrefs, could you provide some context about the proposed change in the description? Adding information such as the reason behind the change, any current problem it could be causing or a description of the code, usually helps us review these PRs easier and faster.

**Comment by stefan-ahrefs** [comment]
Sorry, I thought it's obvious. Flush priviledges after user updates are needed for the changes to take effect. Otherwise the changes will not be effective, but will wait for someone to manually run flush privileges or restart mysql
Failing tests are unrelated to this change. Change is minimal and working well on my production environment.

**Comment by alexjfisher** [comment]
There are other instances of `FLUSH PRIVILEGES` in this provider, but probably also other places where it's needed but not implemented??  I wonder if we should do the same as is done in the `mysql_grant` provider?

https://github.com/puppetlabs/puppetlabs-mysql/blob/1dda4a44bbc4c9022d8c64b787d56b7cb01a50e6/lib/puppet/provider/mysql_grant/mysql.rb#L162-L165

**Comment by LukasAud** [comment]
Closing and reopening PR to rekick automated testing.

**Comment by LukasAud** [comment]
Hi @stefan-ahrefs, we have checked the code and it looks good enough for us, although we will be raising an issue soon to consider implementing @alexjfisher suggestion as a replacement to this and similar code in the future.

Meanwhile, we can merge this change if you can take a look a the current failures. Specifically, the unit tests seem to be throwing failures related to this code:
https://github.com/puppetlabs/puppetlabs-mysql/runs/5788628827?check_suite_focus=true 
https://github.com/puppetlabs/puppetlabs-mysql/runs/5788628950?check_suite_focus=true

These failures seem, at first glance, to be caused by unamended test cases in the spec files. Please review these and make the necessary changes.

**Pull request closed without merging**
