### PR TITLE
set show_diff to false for file with password

### PR DESCRIPTION
**Pull request by applewiskey**
It's no secure to be able to view passwords in logs or interactively.

### CODE REVIEW

**Comment by igalic** [comment]
oh the joy… this fails with older puppets: https://travis-ci.org/puppetlabs/puppetlabs-mysql/jobs/55012360#L2225-L2239

**Comment by petems** [comment]
Yeah, testing things that don't exist in older Puppet is a bit tricky, you need to do something like this:

```
if (Puppet.version >= '3.5.0')
    context "show_diff parameter with puppet #{Puppet.version}" do
      let(:facts) {{ :puppetversion => Puppet.version }}
      it { is_expected.to contain_file('/root/.my.cnf') }
  else
    context "validating content with puppet #{Puppet.version}" do
       let(:facts) {{ :puppetversion => Puppet.version }}
       it { is_expected.to contain_file('/root/.my.cnf') }
    end
  end
```

To ensure the fact is set based on the Puppet version.

**Comment by petems** [comment]
Here's a similar test for the validate_cmd parameter which is Puppet > 3.5 only

https://github.com/arnoudj/puppet-sudo/blob/master/spec/defines/sudo_sudoers_spec.rb#L48

**Comment by igalic** [comment]
btw, the reason for the failing tests:
```
 1) mysql::server on PE3.0 centos-6-x86_64 mysql::server::root_password when root_password set should contain Mysql_user[root@localhost]
     Failure/Error: it { is_expected.to contain_mysql_user('root@localhost') }
     Puppet::Error:
       Evaluation Error: Left match operand must result in a String value. Got an Integer. at /home/travis/build/puppetlabs/puppetlabs-mysql/spec/fixtures/modules/mysql/manifests/server/root_password.pp:24:8 on node testing-worker-linux-docker-73fba05c-3373-linux-16.prod.travis-ci.org
```

**Comment by jonnytpuppet** [comment]
Hi There

I'm closing this PR due to inactivity. It would be great if you could fix the raised concerns and re-open another PR, as I'd love to see this merged!

Thanks!

**Pull request closed without merging**
