### PR TITLE
fix for issue #1502

### PR DESCRIPTION
**Pull request by o4ier**

### CODE REVIEW

**Comment by o4ier** [comment]
Ok, "just a little change" means more I am afraid. I will go back and retry after following the contributing document.

**Comment by GSPatton** [comment]
We are closing this PR due to inactivity. Feel free to reopen if you feel like working on it again. Thanks for your contribution.

**Comment by alaunay** [comment]
We're hit by this too. What's the status of the PR ?

**Comment by o4ier** [comment]
Hello @alaunay 
as mentioned by @GSPatton there are some issues with tests, that I am not "deep" enough in the whole process to fix.
Feel free to fork my code, fix the tests and open your own PR.

**Pull request closed without merging**
