### PR TITLE
(IAC-1677) Fix issue with deprecated rspec

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@pmcmaw check out https://stackoverflow.com/questions/25041974/rspec-pending-results-in-falied-test

I put the comment back to what it was previously when this code was added.

**Comment by ghoneycutt** [comment]
The failing test is a transitory issue downloading an rpm for acceptance testing and not applicable for this change.

**Comment by pmcmaw** [comment]
@ghoneycutt thats interesting! Thanks for that! :-)

**Comment by pmcmaw** [comment]
Merging, 1 failure is a transient error.

**Review by pmcmaw — APPROVED** [review]

**Pull request merged**
