### PR TITLE
fix server_service_name for Debian/stretch

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
Seems I forgot that in #926

**Comment by hunner** [comment]
Merged

**Comment by hunner** [comment]
Odd that it didn't auto-close: https://github.com/puppetlabs/puppetlabs-mysql/commit/81317e5830c682647a6279bf7963803186541e8f

**Comment by mmoll** [comment]
GitHub lags a bit today, thanks!

**Comment by mmoll** [comment]
BTW, there are quite some open PR in this repo, maybe somebody[tm] could a look and roll a release afterwards 💚

**Pull request closed without merging**
