### PR TITLE
Fix regression introduced by PR#1175 for managing CRON package

### PR DESCRIPTION
**Pull request by comport3**
When using the 'puppet-cron' module, the following error was observed when testing release v9.1.0:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Package[cron] is already declared at (file: /etc/puppetlabs/code/environments/production/modules/mysql/manifests/backup/mysqldump.pp, line: 67); cannot redeclare (file: /etc/puppetlabs/code/environments/production/modules/cron/manifests/install.pp, line: 10) (file: /etc/puppetlabs/code/environments/production/modules/cron/manifests/install.pp, line: 10, column: 5) on node`

So in classes in the backup classes the parameter "$manage_package_cron" was added with a default of false to allow a non breaking upgrade, with this being overridable as a top class parameter as needed, eg. using Hiera.

### CODE REVIEW

**Comment by comport3** [comment]
Can someone please review this? It has only failed Travis CI because "Error: Could not find a suitable provider for cron". This is exactly the point of this PR - cron is already being managed externally.

**Comment by sheenaajay** [comment]
Thanks alot for submitting the PR @comport3 .Reviewing the changes.

Could you please update the default value to true for the following param "$manage_package_cron".
Also please add the variable to the public class too (https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/server/backup.pp)
And a unit test case to verify the new parameter added.
And a documentation update for the parameter.

Thanks again for your contribution.

**Comment by vchepkov** [comment]
Default manage_package_cron should not be true. Cron is not part of mysql technology stack and it's managing should be optional. On top of this, this introduces a breaking change as was previously mentioned. IMHO, it should be completely removed from the module. You don't install `coreutils` package to make `test` available, for instance, or `bash`, for the cron scripts. This part should be left to the user

**Comment by comport3** [comment]
Thanks for the feedback @sheenaajay - I have adjusted based on your feedback as follows -

- Moved new parameter into the public Backup class and configured inheritance into the private mysqldump and mysqlbackup classes
- Added the same new logic to the xtradbackup class
- Updated the documentation on usage in REFERENCE.md

In some respects, I agree with @vchepkov - this functionality should be presumed to be handled perfectly fine as an external dependency OR flagged clearly as a likely **breaking change**.

**Comment by sheenaajay** [comment]
@vchepkov Thank you. Yeah make sense the value should be set to false.
@comport3 You can add the unit tests here for both options true and false
https://github.com/puppetlabs/puppetlabs-mysql/blob/master/spec/classes/mysql_server_backup_spec.rb#L22
https://puppet.com/blog/unit-testing-rspec-puppet-for-beginners
Please let me know if you need more information.

**Comment by grant-veepshosting** [comment]
Hi @sheenaajay - can you please review my last commit, and help to resolve the above conflict/s?

**Comment by sheenaajay** [comment]
@grant-veepshosting Changes looks good. You can click on resolve conflicts and get the changes from master. Please find the detailed step here.https://help.github.com/en/articles/resolving-a-merge-conflict-on-github.Please let me know if you need more information.

**Comment by sheenaajay** [comment]
@grant-veepshosting Hope everything is going good. Please let us know if you need more information.

**Comment by grant-veepshosting** [comment]
Hi @sheenaajay - it says only those with Write permissions can resolve Merge conflicts. I don't think I have any write permissions for this. Can you help out to merge this PR please?

**Comment by sheenaajay** [comment]
> Hi @sheenaajay - it says only those with Write permissions can resolve Merge conflicts. I don't think I have any write permissions for this. Can you help out to merge this PR please?

Resolved the conflict.Could you please add a closing brace to the following lines.Thank you.
https://github.com/puppetlabs/puppetlabs-mysql/blob/a5a49d3a3df05cfb4cf4dd4bbb44e3b6972a6978/manifests/backup/mysqlbackup.pp#L80

https://github.com/puppetlabs/puppetlabs-mysql/blob/a5a49d3a3df05cfb4cf4dd4bbb44e3b6972a6978/manifests/backup/mysqldump.pp#L

**Comment by sheenaajay** [comment]
@comport3 Thanks for submitting the PR. We need to resolve the conflicts again. Do you want to open a new PR with the changes?

**Comment by lionce** [comment]
Hello @comport3 ,

Please let us know if you're still working on this PR and if we can help you! Thanks! 

Cheers!

**Comment by sheenaajay** [comment]
@comport3 Thanks for submitting the PR. Resolved conflicts, and fixed the test failures. Move the manage_package_cron to params file. Please review the changes. Thank you.

**Comment by sheenaajay** [comment]
Screen Shot 2020-02-21 at 11 08 25

**Comment by sheenaajay** [comment]
@comport3 Acceptance tests are failing with this fix. Since this hasn't seen any activity in about a month I'm going to go ahead and close this pull request for the time being. Please feel free to re-open this pull request. Thank you for your contribution.

**Pull request closed without merging**
