### PR TITLE
Revert "Use Puppet-Datatype Sensitive"

### PR DESCRIPTION
**Pull request by ghoneycutt**
This reverts commit 8413dbeed33ff866360fba51f2a706f2367b931b.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
The addition of this commit broke unit testing and should not have been merged. The release process seems to have been messed up as this commit in the history should be in the v11.0.3 release though when you check out that tag the commit is missing.


The errors below were introduced with commit 8413dbeed33ff866360fba51f2a706f2367b931b

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) mysql::password behaves like mysql::password function returns Sensitive with sensitive=true
     # should have a Returnvalue of Datatype Sensitive
     Failure/Error: is_expected.to run.with_params('password', true).and_return(sensitive('*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19'))
       expected mysql::password("password", true) to have returned Sensitive("*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19") instead of #<Sensitive [value redacted]>
     Shared Example Group: "mysql::password function" called from ./spec/functions/mysql_password_spec.rb:46
     # ./spec/functions/mysql_password_spec.rb:29:in `block (2 levels) in <top (required)>'
     # /opt/puppetlabs/pdk/share/cache/ruby/2.7.0/bin/rspec:23:in `load'
     # /opt/puppetlabs/pdk/share/cache/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
     # /opt/puppetlabs/pdk/private/ruby/2.7.3/bin/bundle:23:in `load'
     # /opt/puppetlabs/pdk/private/ruby/2.7.3/bin/bundle:23:in `<main>'

  2) mysql::password non-namespaced shim mysql_password behaves like mysql::password function returns Sensitive with sensitive=true
     # should have a Returnvalue of Datatype Sensitive
     Failure/Error: is_expected.to run.with_params('password', true).and_return(sensitive('*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19'))
       expected mysql::password("password", true) to have returned Sensitive("*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19") instead of #<Sensitive [value redacted]>
     Shared Example Group: "mysql::password function" called from ./spec/functions/mysql_password_spec.rb:50
     # ./spec/functions/mysql_password_spec.rb:29:in `block (2 levels) in <top (required)>'
     # /opt/puppetlabs/pdk/share/cache/ruby/2.7.0/bin/rspec:23:in `load'
     # /opt/puppetlabs/pdk/share/cache/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
     # /opt/puppetlabs/pdk/private/ruby/2.7.3/bin/bundle:23:in `load'
     # /opt/puppetlabs/pdk/private/ruby/2.7.3/bin/bundle:23:in `<main>'
```

**Comment by pmcmaw** [comment]
`Pending: (Failures listed here are expected and do not affect your suite's status)
`Please note, these tests are marked as pending, therefore don't actually affect the test suite status.
 I have also ran them locally from `main` with no failures other than what you have highlighted above (but this is not an issue).

`2744 examples, 0 failures, 2 pending` is the final result, a pending test is not a failing or broken test, therefore I don't think this revert is necessary. 

As for the issue with release, I will look into it now.

**Comment by pmcmaw** [comment]
I agree with the issue on release, I can see it was supposed to make the v11.0.3 release but something has happened there, but the fact it is not tagged or included in the CHANGELOG means there is nothing needed on our end right now, other than a release containing the change (this will happen Monday) something slipped through the cracks there.

**Comment by ghoneycutt** [comment]
It shows pending locally though is breaking tests in CI.

**Comment by pmcmaw** [comment]
PR has been merged to stop this breaking, there is something going on with CI as it is pending and passes locally - nice catch! :-) 
https://github.com/puppetlabs/puppetlabs-mysql/pull/1412

**Pull request closed without merging**
