### PR TITLE
(MODULES-8193) - Wrapper methods created for inbuilt 4.x functions

### PR DESCRIPTION
**Pull request by david22swan**
These were created to bridge the gap between the 4.x and 3.x functions and account for the difference in their naming.

### CODE REVIEW

**Comment by david22swan** [comment]
Tested wrappers by replacing mentions of the actual functions within the code.

**Comment by david22swan** [comment]
This pr has been created to allow users to continue to utilize the same function calls after having moved to puppet 4, as the change in naming between the 3.x and 4.x functions would cause breakages i anyone that makes the switch.

**Comment by tphoney** [comment]
Unit tests would be great for this, to show that we at least have the happy path tested.

**Comment by tphoney** [comment]
just waiting on the tests ....

**Comment by david22swan** [comment]
Having some trouble getting the deprecation warning check to work. I've done the wrappers a little differently than how it is in stdlib

**Comment by tphoney** [comment]
So these new wrapper functions, are they mentioned in the readme, do they come out when strings is run ?

**Comment by david22swan** [comment]
Made a strings run, the functions are now in the reference.md.

**Comment by tphoney** [comment]
@david22swan sorry to point it out

**Pull request merged**
