### PR TITLE
Deprecate mysql::server::mysqltuner and show it as an example

### PR DESCRIPTION
**Pull request by ghoneycutt**
Suggest moving `mysql::server::mysqltuner` to an example profile. It is a very simple piece of code that is not directly part of managing mysql and should not be part of the mysql module.

### CODE REVIEW

**Comment by pmcmaw** [comment]
This should go green if you rebase.

**Comment by ghoneycutt** [comment]
@pmcmaw This is ready for merge

**Comment by daianamezdrea** [comment]
Hi @ghoneycutt, I've merged your other PR, I'll merge this one too if you rebase it, thank you for your contributions! Cheers!

**Comment by ghoneycutt** [comment]
Thanks @daianamezdrea , rebased

**Pull request merged**
