### PR TITLE
Improvement to mysql::sql task

### PR DESCRIPTION
**Pull request by alexjfisher**
* Added a new `structured` parameter.  When `true` output from the mysql
will be parsed by the task and returned as structured data.
* MySQL errors are parsed and detailed error objects returned.

### CODE REVIEW

**Comment by alexjfisher** [comment]
Thanks for reviewing this.

I would have liked to have also switched to using[ `puppetlabs-ruby_task_helper`](https://github.com/puppetlabs/puppetlabs-ruby_task_helper).  This would have made adding [unit tests](https://github.com/puppetlabs/puppetlabs-ruby_task_helper#testing) somewhat easier.  As I understand it, this would be a breaking change though as only more modern versions of bolt support  [helper files](https://puppet.com/docs/bolt/latest/writing_tasks.html#sharing-task-code).

Quoting @adreyer from slack.
> Switching to the task helper is a breaking change since multi-file tasks were not supported in PE before 2019.0.1 . I’m not sure if the tasks are considered stable parts of those modules however.

I'll see what I can do.  Maybe I can add some testing regardless.

**Comment by cmccrisken-puppet** [comment]
Hi @alexjfisher - appreciate you looking in to it. If it's something that will cause a time sink, then we can probably merge without the tests. Still in a bit of a learning phase at the moment :)

**Comment by david22swan** [comment]
@alexjfisher Hey, just wondering if this was work that you intended to continue and if there was any help that you needed?

**Comment by sheenaajay** [comment]
@alexjfisher Just wondering is there any more work on this PR. Looks like its ready to merge. Thanks for all your work.

**Comment by michaeltlombardi** [comment]
Since this hasn't seen any activity in over a month I'm going to go ahead and close this pull request for the time being. Please re-open this pull request once the next actions are addressed, new information is available, or you have a question related to this pull request. We've become aware of difficulties re-opening pull requests, in the event you cannot please mention `puppetlabs/modules`  with an @ sign in front and we'll re-open this pull request.

  Closing the pull request doesn't mean we don't consider this change valuable, just that there are things that need to be addressed before it can be merged. If you have any questions or concerns, please don't hesitate to ping us in slack.puppet.com.

**Pull request closed without merging**
