### PR TITLE
Remove references to old_root_password (cleanup)

### PR DESCRIPTION
**Pull request by JCotton1123**
As far as I could tell this parameter is not used anywhere.

### CODE REVIEW

**Comment by JCotton1123** [comment]
I can revise this PR, revert the changes, and just update the README file with a note that this parameter exists for compatibility and doesn't do anything. Does that make sense?

**Comment by JCotton1123** [comment]
I've updated the PR and indicated that `old_root_password` is deprecated.

**Comment by igalic** [comment]
this looks betterer, i think we could merge it as it is, though i'm not sure about the semantics of introducing warnings between versions.

**Comment by JCotton1123** [comment]
Hi, this has been hanging around for a while. Can you please let me know if it needs any additional work to make it mergable.

**Comment by igalic** [comment]
@mhaskel: ping

**Comment by mhaskel** [comment]
@JCotton1123 sorry I missed the updates on this, but looks good now, so thanks!

**Pull request merged**
