### PR TITLE
New Feature Request - Override Default Provider on CentOS 7

### PR DESCRIPTION
**Pull request by jmk61**

### CODE REVIEW

**Comment by DavidS** [comment]
Hi,

it would be great to have a few words about that parameter in the README. Also, thinking about the grander scheme, would it be appropriate to have something to specify the provider directly as `(mariadb|mysql)` instead of trying to fudge around with the auto detection?

**Comment by jmk61** [comment]
David:

I would agree with you on specifying the provider directly. Please reject the pull request and I'll submit a new one with this suggestion in mind and include info in the README.

**Comment by DavidS** [comment]
You can modify you local commit(s) until they look like you want them to look, and then push (--force) them to this branch on github to replace the contents of this PR. That will keep the history and commentary of this change together.

See these docs for manipulating your local branch:
Rebasing: https://git-scm.com/book/en/v2/Git-Branching-Rebasing
Squashing: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by tphoney** [comment]
@jmk61 thanks for the code, you said you wanted this PR closed. The suggestion from @DavidS  is a better way to go about amending a PR.

**Comment by paulhamby** [comment]
@jmk61 Are you still going to submit a new PR with the proposed changes along with info in the README?

Thanks!

**Pull request closed without merging**
