### PR TITLE
do not emit other ssl directives when ssl = false

### PR DESCRIPTION
**Pull request by kjetilho**
This is needed for newer versions of MariaDB, see issue #1509

### CODE REVIEW

**Comment by LukasAud** [comment]
Hi, @kjetilho. Thanks for your contribution. We are currently investigating the issue you are trying to address. Unfortunately, it doesnt seem like our test cases cover this scenario so we will need to investigate a bit further to ensure that your PR does not have any unexpected side effect. Meanwhile, could you implement a test case for your change?

**Comment by kjetilho** [comment]
something like the above?

**Comment by LukasAud** [comment]
Yes, that should be enough. Thanks for your contribution. We will merge as soon as we finish testing it on our side.

**Review by LukasAud — APPROVED** [review]
LGTM

**Pull request merged**
