### PR TITLE
move out $options['mysqld']['log-error'] from service.pp into installdb.pp

### PR DESCRIPTION
**Pull request by ndelic0**
Installation of Percona-Server-57 from yum repository has a side effect - touching of /var/log/mysqld.log. The file is empty and owned by root user, and that prevents mysql datadir initialization. 

puppet-agent[2003]: Execution of '/usr/sbin/mysqld --initialize-insecure --basedir=/usr --datadir=/var/lib/mysql --user=mysql --log-error=/var/lib/mysql/mysqld.log' returned 1
.
Given issue reproduced on CentOS 6.7, possibly on CentOS7.

### CODE REVIEW

**Comment by jonnytpuppet** [comment]
Hey There

Thanks for your contribution!

Are you sure this isn't more of a bug/issue with Percona-Server-57? Can you please explain how moving the resource from one pp to the other solves this?

Thanks!

**Comment by ndelic0** [comment]
Hi jonnytpuppet!

It's a bug with a yum installer. By managing log_error file inside of installdb class we're only changing file ownership, prior to mysql_datadir resource declaration, thus ensuring that mysql --initialize-insecure actually succeed. 
The way I see, though it is a bug with the installer, we're not modifying module logic here, just securing it.

**Comment by jonnytpuppet** [comment]
Hi There

This is not the correct place to move the file resource. It may fix your solution, however then we run the risk of the file not being managed properly.

What we should do, it make the datadir resource depend on the logfile resource (inside the service class).

Thanks

**Comment by ndelic0** [comment]
Hi JT,

Not sure I got this one. If you're suggesting adding dependency for logfile resource inside service class, basically something like this 

`if $options['mysqld']['log-error'] {
    file { $options['mysqld']['log-error']:
      ensure => present,
      owner  => $mysqluser,
      group  => $::mysql::server::mysql_group,
      before => Mysql_datadir[ $options['mysqld']['datadir'] ],
    }`

smells like a dependency cycle here  

  `Class['mysql::server::installdb'] ->
  Class['mysql::server::service'] ->`

**Pull request merged**
