### PR TITLE
Solve issue with repeated restarts if ssl-disable is true

### PR DESCRIPTION
**Pull request by markasammut**
With the current code, if ssl-disable is set to true and restart is set to true, the notify message in the server::config class warning about ssl being disabled causes the service to be restarted on each Puppet run.

I have therefore moved that warning message outside of the server::config class, so that server::config ~> server::service does not trigger a restart of the service on each Puppet run.

### CODE REVIEW

**Comment by markasammut** [comment]
PR will pass test If scientific7 and oraclelinux7 are excluded from xtrabackup tests as per https://github.com/puppetlabs/puppetlabs-mysql/pull/1443

**Comment by daianamezdrea** [comment]
Hello @markasammut , sorry for the late answer but our team went through some transformations, can you rebase your PR in order to have everything green and ready to merge? Thank you and sorry again

**Comment by markasammut** [comment]
Rebased, workflows awaiting approval.

**Comment by LukasAud** [comment]
Reopening to trigger tests again.

**Review by LukasAud — APPROVED** [review]

**Pull request merged**
