### PR TITLE
(MODULES-3539) Allow @ in username

### PR DESCRIPTION
**Pull request by Fogelholk**
Allows having @ in the username (for example 'foo@bar'@'localhost')

### CODE REVIEW

**Comment by david22swan** [comment]
@Fogelholk Unfortunatly your code changes when run through an adhoc pipeline are showing consistent failures against Ubuntu 18.04. The error output is as follows:
```
03:03:05 Failures:
03:03:05 
03:03:05   1) mysql_plugin load plugin works without errors
03:03:05      Failure/Error: execute_manifest(pp, catch_failures: true)
03:03:05      Beaker::TestmodeSwitcher::UnacceptableExitCodeError:
03:03:05        Unacceptable exit code returned: 4. Acceptable code(s): 0, 2
03:03:05        
03:03:05      # ./.bundle/gems/gems/beaker-testmode_switcher-0.4.1/lib/beaker/testmode_switcher/runner_base.rb:31:in `handle_puppet_run_returned_exit_code'
03:03:05      # ./.bundle/gems/gems/beaker-testmode_switcher-0.4.1/lib/beaker/testmode_switcher/beaker_runners.rb:138:in `execute_manifest_on'
03:03:05      # ./.bundle/gems/gems/beaker-testmode_switcher-0.4.1/lib/beaker/testmode_switcher/beaker_runners.rb:114:in `execute_manifest'
03:03:05      # ./.bundle/gems/gems/beaker-testmode_switcher-0.4.1/lib/beaker/testmode_switcher/dsl.rb:13:in `block (2 levels) in <module:DSL>'
03:03:05      # ./spec/acceptance/types/mysql_plugin_spec.rb:52:in `block (3 levels) in <top (required)>'
03:03:05 
03:03:05   2) mysql_plugin load plugin finds the plugin #stdout
03:03:05      Failure/Error: expect(r.stdout).to match(%r{^#{plugin}$}i)
03:03:05        expected "" to match /^example$/i
03:03:05        Diff:
03:03:05        @@ -1,2 +1,2 @@
03:03:05        -/^example$/i
03:03:05        +""
03:03:05        
03:03:05        
03:03:05      # ./spec/acceptance/types/mysql_plugin_spec.rb:57:in `block (4 levels) in <top (required)>'
03:03:05      # ./.bundle/gems/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:93:in `block in on'
03:03:05      # ./.bundle/gems/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
03:03:05      # ./.bundle/gems/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
03:03:05      # ./.bundle/gems/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
03:03:05      # ./.bundle/gems/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:125:in `shell'
03:03:05      # ./spec/acceptance/types/mysql_plugin_spec.rb:56:in `block (3 levels) in <top (required)>'
03:03:05 
03:03:05 Finished in 3 minutes 49.4 seconds (files took 2 minutes 1.2 seconds to load)
03:03:05 136 examples, 2 failures
```

**Comment by Fogelholk** [comment]
I have no idea what those failures are above, I just know that this change works for my setup of usernames running on FreeBSD. If the pr doesn't work I guess you should decline it and I will have to manually edit the files each time I update the module locally :)

**Comment by david22swan** [comment]
@Fogelholk If you rebase your changes onto the current master I could check if the failures were related to an existing issue???

**Comment by david22swan** [comment]
@Fogelholk Closing this one as you opened a second pr

**Pull request closed without merging**
