### PR TITLE
(MODULES-10023) Fix multiple xtrabackup regressions

### PR DESCRIPTION
**Pull request by fraenki**
https://tickets.puppetlabs.com/browse/MODULES-10023

### 1. Regression: xtrabackup nonfunctional due to backup dir change

Currently the xtrabackup provider is nonfunctional when `$incremental_backups` is set to `false`. Performing the backup will produce an error starting with the 2nd run (the very first backup is successful):

```
# /usr/local/sbin/xtrabackup.sh --target-dir=/data/mysql-backup --backup
[...]
xtrabackup: Can't create/write to file '/data/mysql-backup/xtrabackup_logfile' (Errcode: 17 - File exists)
xtrabackup: error: failed to open the target stream for 'xtrabackup_logfile'.
```

This regression was introduced in #1188 with commit https://github.com/puppetlabs/puppetlabs-mysql/commit/155f8a14925e836c91140a3a63693617cc20bbb6. The value of `--target-dir` was changed from

```
${backupdir}/`date +%F_%H-%M-%S`
```

 to just `${backupdir}`.

As a result, every backup is written to the _exact same_ target directory, which is not supported by xtrabackup and results in the above error message. So after performing the first backup (which succeeds because the target directory is still empty), all following backup jobs will fail.

Furthermore, this change renders the `$backuprotate` parameter nonfunctional, because only one backup can be kept this way.

I think this was an oversight and should be seen as a regression, because it effectively breaks xtrabackup for full backups. That's why I propose to revert `--target-dir` back to the old (working) value.

### 2. Regression: backup rotation nonfunctional due to incompatible find

While working on the first regression, I've noticed a second regression that is directly related. #1176 added backup rotation for xtrabackup. However, the `find` that was added in commit https://github.com/puppetlabs/puppetlabs-mysql/commit/9834d9afa9421fec995dad41beb6e3331665cfb7 is incompatible:

```
find "${DIR}/" -maxdepth 1 -type f -name "${PREFIX}*.sql*" -mtime +${ROTATE} -print0 | xargs -0 -r rm -f
```

Issues:
* First of all, the file name pattern is invalid, because xtrabackup does not use the `.sql` file extension, but instead multiple other file types.
* Besides that the `${PREFIX}` is nowhere to be found.
* Finally, `-maxdepth 1` is incompatible, because a backup may contain several (sub-) directories – and every full backup should be stored in it's own directory (see previous regression).

It looks like this `find` was copied from another backup provider, so I propose to change it in a way that deals with xtrabackup's uniqueness. The new approach assumes that every backup (incremental or full) resides in it's own sub-directory, so it's pretty easy to remove an obsolete backup by simply removing the whole directory.

### Small quality of life improvements
While working on fixing the regressions I've implemented small changes that improve the xtrabackup experience:

* For incremental backups:
  * Add a warning if backup rotation is set to less than 7 days, because this would make incremental backups impossible. (A full backup must exist when trying to create an incremental backup, but a full backup is only performed by the weekly cronjob every sunday.)
  * Change the path for the weekly full backup. This is required in order for the backup rotation to work as expected and to make it possible to keep more than one full backup (that is more than 7 days of backups).
* Deal with the GNU/BSD `date` difference.
* Add more comments explaining what this code (or my change) does and why it's important.
* Adjust unit tests accordingly.

### CODE REVIEW

**Comment by fraenki** [comment]
I've successfully verified that both full and incremental backups are working perfectly fine after applying the proposed fixes.

### Full backups
The daily cron job works as expected...
```
/usr/local/sbin/xtrabackup.sh --target-dir=/data/mysql-backup/$(date +%F_%H-%M-%S) --backup
[...]
191017 11:13:57 completed OK!
```

...and produces the following directory structure (depends on the time when the cron job ran):

```
# ls -l /data/mysql-backup/
total 8
drwxr-x--- 9 root root 4096 Oct 17 10:59 2019-10-17_10-59-12/
drwxr-x--- 9 root root 4096 Oct 17 11:13 2019-10-17_11-13-52/
```

Note: I ran the cron job twice manually for this test case.

### Incremental backups
The weekly cronjob creates the full backup just fine...

```
/usr/local/sbin/xtrabackup.sh --target-dir=/data/mysql-backup/$(date +%F)_full --backup
[...]
191017 11:10:54 completed OK!
```
...and the daily cron job is able to perform incremental backups based on the weekly full backup;

```
/usr/local/sbin/xtrabackup.sh --incremental-basedir=/data/mysql-backup/$(date -d "last sunday" +%F)_full --target-dir=/data/mysql-backup/$(date +%F_%H-\%M-%S) --backup
[...]
incremental backup from 86330169 is enabled.
[...]
xtrabackup: using the full scan for incremental backup
[...]
xtrabackup: The latest check point (for incremental): '86330169'
[...]
xtrabackup: Transaction log of lsn (86330169) to (86330178) was copied.
191017 11:11:50 completed OK!
```

...and it produces the following directory structure (depends on the time when the cron job ran):

```
# ls -l /data/mysql-backup/
total 12
drwxr-x--- 9 root root 4096 Oct 17 11:10 2019-10-13_full/
drwxr-x--- 9 root root 4096 Oct 17 11:11 2019-10-17_11-11-46/
drwxr-x--- 9 root root 4096 Oct 17 11:13 2019-10-17_11-13-16/
```

Note: I had to rename the manually created first full backup to match last sunday's date to make this manual test case work. But I'm confident that the cron job works perfectly fine now, I just did not want to wait until sunday :)

**Comment by cmccrisken-puppet** [comment]
@fraenki Thanks for the PR, the comprehensive descriptions and test coverage you've added. Looking through the change with my colleagues and we'll get back to you a.s.a.p.

**Comment by cmccrisken-puppet** [comment]
@fraenki After some discussion internally, we were thinking it might be good to add an acceptance test for the xtrabackup functionality to ensure we don't run in to this scenario again. Do you feel that's something you can add? We can help / support if needs be.

**Comment by fraenki** [comment]
@cmccrisken-puppet Sure, I'll have a look. Are there any existing acceptance tests from Puppetlabs that I should use as a reference? (I assume Litmus is the way to go, right?)

**Comment by lionce** [comment]
Hello @fraenki ,

You can check module's tests for reference. For running acceptance tests we're using puppet_litmus. To run the acceptance tests follow the instructions from this point [here](https://github.com/puppetlabs/puppet_litmus/wiki/Tutorial:-use-Litmus-to-execute-acceptance-tests-with-a-sample-module-(MoTD)#install-the-necessary-gems-for-the-module). Please let us know if you need help/support :) 

Cheers!

**Comment by fraenki** [comment]
>You can check module's tests for reference.

@lionce Before I dive into this: are the module's tests expected to run without failure? Because they ALL fail for me:

```
Finished in 1 minute 34.35 seconds (files took 2.05 seconds to load)
47 examples, 47 failures

```

**Comment by lionce** [comment]
Hey @fraenki ,

The tests should be successfully ran. Can you please provide me the errors? Also your set-up steps please? maybe the platform is not completely configured. 

e.g. you can check all the steps and the results here on [travis report](https://travis-ci.org/puppetlabs/puppetlabs-mysql/jobs/598885069?utm_medium=notification&utm_source=github_status)
```
26.64s$ bundle exec rake 'litmus:provision_list[travis_el7]'
26.15s$ bundle exec rake 'litmus:install_agent[puppet6]'
13.59s$ bundle exec rake litmus:install_module
873.26s$ bundle exec rake litmus:acceptance:parallel
```

```
travis_el7:
  provisioner: docker_exp
  images: ['waffleimage/centos7', 'waffleimage/oraclelinux7', 'waffleimage/scientificlinux7']
```

If you want to provision just one platform, you should use:
`bundle exec rake 'litmus:provision[docker_exp, waffleimage/centos7]'`

Cheers!

**Comment by fraenki** [comment]
@cmccrisken-puppet @lionce 

I've added the following to this PR:

* acceptance tests for xtrabackup
* merged #1244 into this PR in order to be able to add complete acceptance tests
* fixed default of `$xtrabackup_package_name` on CentOS 6 (which was revealed by new acceptance tests)
* added xtrabackup information to the README

One step closer, only two failures that I can't explain:

*  [PLATFORMS=deb_puppet5](https://travis-ci.org/puppetlabs/puppetlabs-mysql/jobs/633456358) reports an issue that does not seem to be related to my changes.
*  [PLATFORMS=el6_puppet5](https://travis-ci.org/puppetlabs/puppetlabs-mysql/jobs/633456361) fails to fetch the Percona repository metadata.

Any advice on these two issues? :)

**Comment by sheenaajay** [comment]
@fraenki Reopening the PR to rerun the Travis jobs. Thank you.

**Comment by carabasdaniel** [comment]
Hi @fraenki,

Both these failures seem to be related to the installation of the percona package and its dependencies:
- For Debian: ` The following packages have unmet dependencies:
        percona-release : Depends: gnupg2 but it is not going to be installed
       E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).`
- For the PLATFORMS=el6_puppet5 it seems to be problems with the metadata to install the percona package for some of the OSes tested

I recommend you try to run the installation of the percona package manually from inside the containers to debug these issues a bit easier. Using Litmus you can provision the images on your machine using: 
`bundle exec rake litmus:provision['docker_exp','waffleimage/debian8']`
In order to run the tests install the puppet agent and module using `bundle exec rake litmus:install_agent[puppet5]` and `bundle exec rake litmus:install_module` 

In your inventory.yaml (will be created after the provisioning) file you will find the necessary details to ssh into the container and run manually from there.

**Comment by fraenki** [comment]
@carabasdaniel Thanks for the hints. All tests are working now. Ready for merge :)

(Fixes in https://github.com/puppetlabs/puppetlabs-mysql/pull/1245/commits/3e0e11af5f60870811d69f8500dd16b68bcb575f: On Debian and older versions of Ubuntu the xtrabackup package name was wrong. Debian also requires the gnupg2 package. On Scientific Linux 6 the value of $releasever in YUM differs from RedHat/CentOS, making the Percona repo incompatible; as a workaround $releasever is set to the same value that works on RedHat/CentOS.)

**Comment by carabasdaniel** [comment]
Hi @fraenki 

Thanks again for submitting this PR. Looks really great now.

In order to get this PR merged we have to ensure that this feature works on all the OSs this module supports. 

Running the full suite of acceptance tests seems to point out there are still failures on installing percona-xtrabackup on a few machines:
```┌ [✖] Running against 19 targets.
├── [✖] stepwise-octet.delivery.puppetlabs.net, redhat-5-x86_64
├── [✔] hectic-impulse.delivery.puppetlabs.net, redhat-6-x86_64
├── [✔] sylvan-inflow.delivery.puppetlabs.net, redhat-7-x86_64
├── [✖] barefooted-hex.delivery.puppetlabs.net, redhat-8-x86_64
├── [✖] amazing-stench.delivery.puppetlabs.net, centos-5-x86_64
├── [✔] galactic-misery.delivery.puppetlabs.net, centos-6-x86_64
├── [✔] amber-longhand.delivery.puppetlabs.net, centos-7-x86_64
├── [✖] token-trapper.delivery.puppetlabs.net, oracle-5-x86_64
├── [✖] master-cement.delivery.puppetlabs.net, oracle-6-x86_64
├── [✔] holy-initiation.delivery.puppetlabs.net, oracle-7-x86_64
├── [✔] dread-pulsation.delivery.puppetlabs.net, scientific-6-x86_64
├── [✔] pleasant-ileum.delivery.puppetlabs.net, scientific-7-x86_64
├── [✔] uncanny-drywall.delivery.puppetlabs.net, debian-8-x86_64
├── [✔] central-analyst.delivery.puppetlabs.net, debian-9-x86_64
├── [✔] snappy-hairpin.delivery.puppetlabs.net, debian-10-x86_64
├── [✖] fool-pedal.delivery.puppetlabs.net, sles-11-x86_64
├── [✔] granular-sponge.delivery.puppetlabs.net, ubuntu-1404-x86_64
├── [✔] sappy-homestead.delivery.puppetlabs.net, ubuntu-1604-x86_64
└── [✔] nocturnal-logic.delivery.puppetlabs.net, ubuntu-1804-x86_64```

On RedHat-8: ``` Error: Execution of '/usr/bin/dnf -d 0 -e 1 -y install percona-xtrabackup' returned 1: Error: Unable to find a match```
On SLES: ``` Error: Execution of '/usr/bin/zypper --quiet install --auto-agree-with-licenses --no-confirm percona-xtrabackup' returned 104```
On CentOS-5 and RedHat-5: ```Error: Execution of '/bin/rpm -i http://repo.percona.com/yum/percona-release-latest.noarch.rpm' returned 1: warning: /var/tmp/rpm-xfer.hzr0u8: Header V4 DSA signature: NOKEY, key ID cd2efd2a
       error: Failed dependencies:
       	rpmlib(FileDigests) <= 4.6.0-1 is needed by percona-release-1.0-14.noarch
       	rpmlib(PayloadIsXz) <= 5.2-1 is needed by percona-release-1.0-14.noarch```
 
If you need help in getting this tests working, please let us know.

**Comment by fraenki** [comment]
@carabasdaniel I've addressed these issues in https://github.com/puppetlabs/puppetlabs-mysql/pull/1245/commits/7d43a58bf15199db6a82db58b7e67310a1378e34. How can I run this "full suite of acceptance tests"?

Besides that after the latest commit the RHEL6/7 tests fail on travis, although they work perfectly fine locally. No idea how this travis "timeout" error should be useful to anyone.

**Comment by sheenaajay** [comment]
@fraenki Thank you for incorporating the comments. We use vmpoolers to run the full acceptance tests. It is failing with following error
` Error: Execution of '/bin/rpm -i http://repo.percona.com/yum/release/5/os/noarch/percona-release-0.1-5.noarch.rpm' returned 1: warning: /var/tmp/rpm-xfer.gdrIa5: Header V4 DSA signature: NOKEY, key ID cd2efd2a
       error: Failed dependencies:
       	rpmlib(FileDigests) <= 4.6.0-1 is needed by percona-release-0.1-5.noarch
       	rpmlib(PayloadIsXz) <= 5.2-1 is needed by percona-release-0.1-5.noarch
       Error: /Stage[main]/Main/Package[percona-release]/ensure: change from 'absent' to 'present' failed: Execution of '/bin/rpm -i http://repo.percona.com/yum/release/5/os/noarch/percona-release-0.1-5.noarch.rpm' returned 1: warning: /var/tmp/rpm-xfer.gdrIa5: Header V4 DSA signature: NOKEY, key ID cd2efd2a
       error: Failed dependencies:
       	rpmlib(FileDigests) <= 4.6.0-1 is needed by percona-release-0.1-5.noarch
       	rpmlib(PayloadIsXz) <= 5.2-1 is needed by percona-release-0.1-5.noarch
       Error: Execution of '/bin/rpm -i https://download.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm' returned 1: error: skipping https://download.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm - transfer failed - Unknown or unexpected error
       Error: /Stage[main]/Main/Package[epel-release]/ensure: change from 'absent' to 'present' failed: Execution of '/bin/rpm -i https://download.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm' returned 1: error: skipping https://download.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm - transfer failed - Unknown or unexpected error
       Error: Could not find package percona-xtrabackup-20
       Error: /Stage[main]/Mysql::Backup::Xtrabackup/Package[percona-xtrabackup-20]/ensure: change from 'purged' to 'present' failed: Could not find package percona-xtrabackup-20`

**Comment by fraenki** [comment]
@david22swan Thanks for fixing the travis tests! :+1: 

@sheenaajay I've addressed the CentOS/RHEL 5 errors in https://github.com/puppetlabs/puppetlabs-mysql/pull/1245/commits/3efa12355b87c1354a748f69abdd7f9db7c57eb1. However, RHEL5 is EOL so the available docker images are pretty useless and couldn't run all tests. I couldn't find docker images SLES11 so I can't test it at all. Regarding the EL6 failures: Why don't these failures show up in travis, or: why does Puppetlabs use different images for the final tests? Since I can't trigger these failures, I have to ask you for the full error messages for all EL6-like operating systems.

**Comment by sheenaajay** [comment]
@fraenki 

Thank you for incorporating the comments. For  PR level we perform testing on the following docker images which are available (debian8 debian9 debian10 ubuntu14.04 ubuntu16.04 ubuntu18.04 centos6 scientificlinux6 centos7 oraclelinux7 scientificlinux7)

But during bug fix or release testing, we cover most of the remaining supported platforms during the testing. Will send you the error information for the failing platform.

**Comment by sheenaajay** [comment]
Hi @fraenki ,Please find the failures below. Let us know if you need more information.

sles-11-x86_64

`Failures:

  1) with xtrabackup enabled should work with no errors when configuring mysql backup
     On host `advisable-pad.delivery.puppetlabs.net'
     Failure/Error: idempotent_apply(pp)
     RuntimeError:
       apply manifest expected no changes
       ` puppet apply /tmp/manifest_20200309_18204_161fzrt.pp --detailed-exitcodes`
       ====== Start output of Puppet apply with unexpected changes ======
       Error: Execution of '/usr/bin/zypper --quiet install --auto-agree-with-licenses --no-confirm xtrabackup' returned 104: Problem retrieving the repository index file for service 'spacewalk':
       [|] This client is not registered to any spacewalk server.

       No provider of 'xtrabackup' found.
       Error: /Stage[main]/Mysql::Backup::Xtrabackup/Package[xtrabackup]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/bin/zypper --quiet install --auto-agree-with-licenses --no-confirm xtrabackup' returned 104: Problem retrieving the repository index file for service 'spacewalk':
       [|] This client is not registered to any spacewalk server.

       No provider of 'xtrabackup' found.
       Warning: /Stage[main]/Mysql::Backup::Xtrabackup/Cron[xtrabackup-weekly]: Skipping because of failed dependencies
       Warning: /Stage[main]/Mysql::Backup::Xtrabackup/Cron[xtrabackup-daily]: Skipping because of failed dependencies
       Notice: Compiled catalog for advisable-pad.delivery.puppetlabs.net in environment production in 0.43 seconds
       Notice: /Stage[main]/Mysql::Backup::Xtrabackup/Cron[xtrabackup-weekly]: Dependency Package[xtrabackup] has failures: true
       Notice: Applied catalog in 1.02 seconds

       ====== End output of Puppet apply with unexpected changes ======

      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:317:in `report_puppet_apply_change'
      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:77:in `apply_manifest'
      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:13:in `idempotent_apply'
      ./spec/acceptance/mysql_backup_spec.rb:207:in `block (3 levels) in <top (required)>'`


oracle-5-x86_64
redhat-7-x86_64
centos-5-x86_64
oracle-6-x86_64

`Failures:

  1) with xtrabackup enabled should work with no errors when configuring mysql backup
     On host `citrated-dive.delivery.puppetlabs.net'
     Failure/Error: idempotent_apply(pp)
     RuntimeError:
       apply manifest expected no changes
       ` puppet apply /tmp/manifest_20200309_18202_2bhhwo.pp --detailed-exitcodes`
       ====== Start output of Puppet apply with unexpected changes ======
       Error: Execution of '/bin/rpm -i https://archives.fedoraproject.org/pub/archive/epel/epel-release-latest-5.noarch.rpm' returned 1: error: skipping https://archives.fedoraproject.org/pub/archive/epel/epel-release-latest-5.noarch.rpm - transfer failed - Unknown or unexpected error
       Error: /Stage[main]/Main/Package[epel-release]/ensure: change from 'absent' to 'present' failed: Execution of '/bin/rpm -i https://archives.fedoraproject.org/pub/archive/epel/epel-release-latest-5.noarch.rpm' returned 1: error: skipping https://archives.fedoraproject.org/pub/archive/epel/epel-release-latest-5.noarch.rpm - transfer failed - Unknown or unexpected error
       Error: Execution of '/usr/bin/yum -e 0 -y install percona-xtrabackup-20' returned 1: Error: failure: repodata/0382344d75a4d35e9bdbb2d4e0bda5fe7a755e07f8c8b1346a88ba3e5a8e64f5-primary.sqlite.bz2 from percona-release-noarch: [Errno 256] No more mirrors to try.
       Error: /Stage[main]/Mysql::Backup::Xtrabackup/Package[percona-xtrabackup-20]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/yum -e 0 -y install percona-xtrabackup-20' returned 1: Error: failure: repodata/0382344d75a4d35e9bdbb2d4e0bda5fe7a755e07f8c8b1346a88ba3e5a8e64f5-primary.sqlite.bz2 from percona-release-noarch: [Errno 256] No more mirrors to try.
       Warning: /Stage[main]/Mysql::Backup::Xtrabackup/Cron[xtrabackup-weekly]: Skipping because of failed dependencies
       Warning: /Stage[main]/Mysql::Backup::Xtrabackup/Cron[xtrabackup-daily]: Skipping because of failed dependencies
       Notice: Compiled catalog for citrated-dive.delivery.puppetlabs.net in environment production in 0.42 seconds
       Notice: /Stage[main]/Mysql::Backup::Xtrabackup/Cron[xtrabackup-weekly]: Dependency Package[percona-xtrabackup-20] has failures: true
       Notice: Applied catalog in 1.42 seconds

       ====== End output of Puppet apply with unexpected changes ======

      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:317:in `report_puppet_apply_change'
      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:77:in `apply_manifest'
      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:13:in `idempotent_apply'
      ./spec/acceptance/mysql_backup_spec.rb:207:in `block (3 levels) in <top (required)>'`


redhat-8-x86_64

`Failures:

  1) with xtrabackup enabled should work with no errors when configuring mysql backup
     On host `hurt-abjection.delivery.puppetlabs.net'
     Failure/Error: idempotent_apply(pp)
     RuntimeError:
       apply manifest expected no changes
       ` puppet apply /tmp/manifest_20200309_18189_u4ene2.pp --detailed-exitcodes`
       ====== Start output of Puppet apply with unexpected changes ======
       Notice: Compiled catalog for hurt-abjection.delivery.puppetlabs.net in environment production in 0.33 seconds
       Notice: /Stage[main]/Main/Package[epel-release]/ensure: created
       Notice: Applied catalog in 1.46 seconds

       ====== End output of Puppet apply with unexpected changes ======

      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:317:in `report_puppet_apply_change'
      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:77:in `apply_manifest'
      ./.bundle/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/puppet_helpers.rb:13:in `idempotent_apply'
      ./spec/acceptance/mysql_backup_spec.rb:207:in `block (3 levels) in <top (required)>'
`

**Comment by fraenki** [comment]
@sheenaajay Commit https://github.com/puppetlabs/puppetlabs-mysql/pull/1245/commits/1f8eefc1a50a3a7964e3d3dd0ae89beb223eb302 disables the new xtrabackup tests on all EOL operating systems, so it should finally pass in your internal tests.

NOTE: Other tests started failing, because the tests are now run on Puppet 6.14 – [this Puppet Agent bug](https://tickets.puppetlabs.com/browse/PUP-10365) is to blame. No failures when running these tests on Puppet 6.13 or Puppet 6 nightly (aka 6.15 prerelease).

@sheenaajay **Please**, if there's yet another minor issue that could easily be fixed, may I ask you to just merge this PR and commit the fix afterwards? It's been 5 months already, and this is starting to get really frustrating.

**Comment by sheenaajay** [comment]
@fraenki Sorry for the delay. Will be talking to the team on priority to review this PR. We can fi the minor problems too. Thanks alot for your contribution. Much appreciated your help.

**Comment by sheenaajay** [comment]
@fraenki The PR is top of the list to get it merged. There is small change to exclude it from running on Oracle 6 box the (os[:family] is Redhat instead of redhat). We will do the changes now.
All the tests are running clean on puppet agent 5. As you have mentioned there is a defect on puppet agent 6.14 version and the agent team will be doing a release in April.
If we accept this PR the tests will be failing on PR level and on release checks.
We will merge this PR as soon as the release from the agent team is available. Hope that's ok. Thanks again for a great PR.

**Comment by sheenaajay** [comment]
Screenshot 2020-05-12 at 13 40 18

**Pull request merged**
