### PR TITLE
Allow empty user passwords

### PR DESCRIPTION
**Pull request by disappear89**
https://tickets.puppetlabs.com/browse/MODULES-7187

Changes: Allow empty user / root password.

Before this PR: Can`t set empty passwords cause of the mysql_user provider failure:
Error: Only mysql_native_password (*ABCD...XXX) hashes are supported.
Error: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]/password_hash: change from [old password hash redacted] to [new password hash redacted] failed: Only mysql_native_password (*ABCD...XXX) hashes are supported.

After this PR: Can set empty passwords cause regex of mysql_user providers password check extended:
Info: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]: Filebucketed /root/.my.cnf to puppet with sum 9d96b07caeee3d0e3e7fb49e0f891860
Notice: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]/content: content changed '{md5}9d96b07caeee3d0e3e7fb49e0f891860' to '{md5}337598bf15a160df1e57d2d90d5bc426'
[root@vmxxxxxx ~]# cat /root/.my.cnf
### MANAGED BY PUPPET ###

[mysql]
user=root
host=localhost
password=''
socket=/tmp/mysql.sock

### CODE REVIEW

**Comment by david22swan** [comment]
@disappear89 Please add a test to account for an empty password

**Comment by david22swan** [comment]
@disappear89 The test looks good, but your changes seem to have disappeared

**Comment by disappear89** [comment]
@david22swan That was by purpose to see if the test works. But travis build does not detect an error but it should.

**Comment by disappear89** [comment]
@david22swan  Any idea? Someone else that could have a look at the test :) ?

**Comment by david22swan** [comment]
@disappear89  Have you tried manually setting an empty password to see what happens?

**Comment by disappear89** [comment]
@david22swan  That`s working. We use the forged repo with my changes on our puppet setup and empty mysql passwords are possible ;)

**Comment by david22swan** [comment]
@disappear89 Have you tried entering an empty password without your changes?

**Comment by disappear89** [comment]
@david22swan Yes than the error Error: 
`Only mysql_native_password (*ABCD...XXX) hashes are supported`
will appear.

**Comment by david22swan** [comment]
@disappear89 Can you recommit the actual changes so that I can see them

**Comment by disappear89** [comment]
@david22swan Done =)

**Comment by david22swan** [comment]
@disappear89 I apologize but after conferring with members of my team there has been some question on why you wish this functionality to be added.

**Comment by disappear89** [comment]
@david22swan No problem. We have setups where some users can connect without password but only via localhost.

**Comment by david22swan** [comment]
@disappear89 Could you add a docs change to reflect this added functionality??

**Comment by disappear89** [comment]
@david22swan  Thanks

**Pull request merged**
