### PR TITLE
Ticket Forge Modules / MODULES-2675 - Unique server_id

### PR DESCRIPTION
**Pull request by jmk61**
Ticket Forge Modules / MODULES-2675
Fixed Unique server_id facter fact. Allowing a unique id to be generated by reading in all 6 splits of the mac address, where as it was only reading in 4 of the 6 splits.

### CODE REVIEW

**Comment by DavidS** [comment]
Hi @jmk61 , thanks for your contribution! Would you be son nice and squash this into a single commit, so as to keep the history clean?

See Squashing: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

**Comment by DavidS** [comment]
A more difficult question: how is this fact used, and how will changing it's output impact the users of this?

**Comment by jmk61** [comment]
The fact is used to determine a unique server ID within the my.cnf which allows master-slave setups. By modifying the fact it will change the users server_id within their conf. It shouldn't have a direct effect on existing setups as I'm unware of a way to directly utilize this information within a setup other then distinguishing each mysql server in your setup.

Please let me know your thoughts, questions and concerns.

Thanks

Joseph Karns
System Administrator III
Penn State University
Outreach Information Technology
329 Innovation Blvd
Suite 306
State College, Pa 16803

----- Reply message -----

**Comment by jmk61** [comment]
David:

Not sure if I did the squash correct. If not request the pull request and I'll resubmit.

Thanks
Joey

**Comment by DavidS** [comment]
Yeah, this branch doesn't look like it should. Also, I'm still not 100% clear what happens to an existing replication setup, when all the `server_id`s change. The docs don't seem to address that.

**Comment by DavidS** [comment]
Closing in preference to #767

**Pull request closed without merging**
