### PR TITLE
support for root password hashes

### PR DESCRIPTION
**Pull request by nassarmu**
adding support for a root_hash as an alternative to root_password.

root_hash and root_password are mutually exclusive and root_hash will also disable my.cnf creation

### CODE REVIEW

**Comment by tphoney** [comment]
@nassarmu thanks for the time and effort you have put into writing this code. It is much appreciated. I have a few suggestions to make before this can be merged.
- Can you add documentation to explain the new behaviour in the README
- Can you squash your commits
- Can you add at least some testing for this new feature

**Comment by tphoney** [comment]
@nassarmu did you mean to close this ?

**Comment by nassarmu** [comment]
Yeah, upon further testing I came across a showstopping bug. Teaches me for
doing this on a Friday.

I am going to have to rethink this before I submit another pull.
On Jun 16, 2016 09:30, "TP Honey" <notifications@github.com> wrote:

@nassarmu <https://github.com/nassarmu> did you mean to close this ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/puppetlabs/puppetlabs-mysql/pull/854#issuecomment-226502672>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABzY1v8vqDo1LB-fjraCepWvCKfZuG0Cks5qMV4YgaJpZM4IzAr1>
.

**Comment by tphoney** [comment]
Thanks for looking into it though.

**Comment by igalic** [comment]
@nassarmu maybe you wanna share with us what the showstopper was, maybe we can help?

**Comment by nassarmu** [comment]
The module assumes the existence of a valid my.cnf to work, so after
setting a root hash it is no longer able to authenticate to mysql and
subsequent runs fail.

Once I'm back at my desk tomorrow I'll post puppet traces

**Pull request closed without merging**
