### PR TITLE
(MAINT) Removing CentOS 7, 8 OS support as both version are EOL

### PR DESCRIPTION
**Pull request by Ramesh7**
## Summary

Removing CentOS 7, 8 OS support as both version are EOL

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Comment by alexjfisher** [comment]
Same question as in https://github.com/puppetlabs/puppetlabs-mysql/pull/1637#issuecomment-2210636893

**Comment by Ramesh7** [comment]
> Same question as in [#1637 (comment)](https://github.com/puppetlabs/puppetlabs-mysql/pull/1637#issuecomment-2210636893)

EL7 you mean CentOS 7? If yes then yes. Have observed that PE team is working on to the same to remove it.
Also as the CentOS 7 EOL was on 30th June, so releasing new module with major version so I think its needed step as well.
Open for thoughts.
BTW the latest agent support is already removed for CentOS 7,8 and Debian 10.

**Comment by alexjfisher** [comment]
> BTW the latest agent support is already removed for CentOS 7,8 and Debian 10.

Really? https://yum.puppetlabs.com/puppet8/el/7/x86_64/puppet-agent-8.7.0-1.el7.x86_64.rpm (Or did I misunderstand?)

**Comment by Ramesh7** [comment]
> > BTW the latest agent support is already removed for CentOS 7,8 and Debian 10.
> 
> Really? https://yum.puppetlabs.com/puppet8/el/7/x86_64/puppet-agent-8.7.0-1.el7.x86_64.rpm (Or did I misunderstand?)

Hi @alexjfisher, I connected with a PE engineer, and it turns out I was mistaken. My apologies for the confusion; I didn’t have the full context. I’ve learned that while PE support for EL7 has been discontinued, the agent is still supported.

**Comment by alexjfisher** [comment]
> > > BTW the latest agent support is already removed for CentOS 7,8 and Debian 10.
> > 
> > 
> > Really? https://yum.puppetlabs.com/puppet8/el/7/x86_64/puppet-agent-8.7.0-1.el7.x86_64.rpm (Or did I misunderstand?)
> 
> Hi @alexjfisher, I connected with a PE engineer, and it turns out I was mistaken. My apologies for the confusion; I didn’t have the full context. I’ve learned that while PE support for EL7 has been discontinued, the agent is still supported.

Ah right.  So installing PE on EL7 isn't supported, but it is a supported agent platform.  In which case I might still have thought that the PE supported modules should continue to support the supported agents??

**Comment by Ramesh7** [comment]
> > > > BTW the latest agent support is already removed for CentOS 7,8 and Debian 10.
> > > 
> > > 
> > > Really? https://yum.puppetlabs.com/puppet8/el/7/x86_64/puppet-agent-8.7.0-1.el7.x86_64.rpm (Or did I misunderstand?)
> > 
> > 
> > Hi @alexjfisher, I connected with a PE engineer, and it turns out I was mistaken. My apologies for the confusion; I didn’t have the full context. I’ve learned that while PE support for EL7 has been discontinued, the agent is still supported.
> 
> Ah right. So installing PE on EL7 isn't supported, but it is a supported agent platform. In which case I might still have thought that the PE supported modules should continue to support the supported agents??

Yeah agreed.

**Comment by Ramesh7** [comment]
Closing this as the removing platforms are supported.

**Pull request closed without merging**
