### PR TITLE
Support Debian/stretch

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
rebased to get green tests

**Comment by mmoll** [comment]
anybody?

**Comment by ekohl** [comment]
Looks like metadata.json wasn't modified to reflect the support.

**Comment by mmoll** [comment]
#965

**Comment by eputnam** [comment]
strictly speaking, this PR updated for Debian 9 _compatibility_ not _support_. We don't officially support Debian 9 yet. when we do, we'll update the metadata to reflect that.

**Pull request merged**
