### PR TITLE
Add option to specify $backupdir as a symlink target, for use with dm…

### PR DESCRIPTION
**Pull request by comport3**
…_crypt encrypted partitions.

### CODE REVIEW

**Comment by tphoney** [comment]
Thanks for the PR, @comport3 . Could you add to the documentation, about this great new functionality. 
optional, squash your commits

**Comment by comport3** [comment]
Yes of course. Is the correct file to do this in the CHANGELOG.md ?

Otherwise, here's the new functionality -

Within the class mysql::backup::mysqldump, there is not the ability to change the default behaviour of backing up to a 'directory' to a 'symlink' instead.

The specific use case it solved for us was to ensure backups were stored on a LUKS/DM Crypt based encrypted partition, but could also be handy for environments using NFS shared and similar redirection.

Usage (Hiera)
```
mysql::backup::mysqldump::mysqlbackupdir_ensure: link
mysql::backup::mysqldump::mysqlbackupdir_target: /mnt/mysqldumps
```

**Comment by tphoney** [comment]
Normally it would go into the top of the file. But because this is a private class, there is no docs in the file. For this to be useful for all users, https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/server/backup.pp should be updated to include these new parameters. As it would be useful for all of the backup providers.

**Comment by tphoney** [comment]
Thanks for the pr @comport3 :)

**Pull request merged**
