### PR TITLE
Using mariadb in OpenSuSE >= 13.1.

### PR DESCRIPTION
**Pull request by sharumpe**
I would like to use MariaDB instead of MySQL on OpenSuSE 13.1. Looking at what has been done for other operatingsystem versions in the source (manifests/params.pp), it appears that you have settled on using operatingsystemrelease to determine when to select mariadb packages, so I have done the same for OpenSuSE.  Hopefully I have done this is a way that works for your process; I'm kind of new to contributing to other folks' projects.

Ticket: https://tickets.puppetlabs.com/browse/MODULES-1337

### CODE REVIEW

**Comment by sharumpe** [comment]
Well, long delay.  Sorry.  I am really not sure what needs to be done to
re-base, however, it looks like there are very few differences between the
current params.pp file and what I have, specifically in the section that
chooses the packages for OpenSuSE.

If it's not too much trouble, could you tell me what I need to do to rebase
my fork?

If not, I may just start a new fork from the current head and re-apply my
changes.  Seems to be the simplest, if not the most "correct", way to go.

Sorry for my lack of knowledge -- most of my work in the past has been on
my own, but I'm trying to learn.  :)

Thanks,
Tim

**Comment by mhaskel** [comment]
Hi @sharumpe, so to rebase you'll need to do something like
```
git fetch upstream
git rebase upstream/master
```
then resolve the conflicts, and 
```
git add <conflicting file>
git rebase --continue
git push -f origin ticket/MODULES-1337-MariaDB_for_OpenSuSE_13.1
```

**Comment by DavidS** [comment]
Hi @sharumpe , thanks for the work you have put in to this pull request. However due to inactivity and this cannot be merged as is this pull request is being closed. If you want to re-submit this PR with the necessary changes, we will gladly look at the new pull request.

**Comment by sharumpe** [comment]
Wow time flies.  I have re-done this change against a new clone of this module from a few days ago. Should I re-open the previous issue or create a new one?

**Comment by sharumpe** [comment]
Wow time flies.  I have re-done this change against a new clone of this module from a few days ago. Should I re-open the previous issue or create a new one?

**Comment by DavidS** [comment]
@sharumpe thanks! It would be great if you could (force) push to here and re-open, so the context is preserved.

**Comment by sharumpe** [comment]
OK, I've pushed the updated code to that same branch, and it looks like the Travis checks are good.

**Comment by igalic** [comment]
\o/ thanks @sharumpe!

**Pull request merged**
