### PR TITLE
MODULES-6027 - enable mysql::server::monitor

### PR DESCRIPTION
**Pull request by spencerbutler**
This patch resolves the issue of the Monitor Class not doing it's job in a hiera environment.

### CODE REVIEW

**Comment by pmcmaw** [comment]
Hey @spencerbutler, I can see the changes have introduced a few regressions in the test suite. When these are resolved I can get this change merged for you. Thank you for taking your time to submit this PR.

**Comment by spencerbutler** [comment]
With regards to the following warning from 'puppet apply', are we able to test this with a version 4 or above hiera environment?

Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5

**Comment by pmcmaw** [comment]
When updating Hiera to version 5 it introduces backwards compatibility. 
If you would like to upgrade to Hiera 5 I would suggest creating a separate PR. 

In this case we would release the module before Hiera 5 is introduced and then again with an x bump when the PR is merged. Hiera 5 has been introduced in our ntp module. Here is an example of a PR for implementation: https://github.com/puppetlabs/puppetlabs-ntp/pull/428/files

Please note the Hiera change is not required to get this PR merged, the only issue is the failing tests which are unrelated to the Hiera warning. If they are resolved I will merged the PR with the Hiera warning. 

Many Thanks
Paula :-)

**Comment by eputnam** [comment]
@spencerbutler, thanks for the PR. I'm going to close this due to inactivity. Please feel free to re-open it if you get some time to continue work on it.

**Pull request closed without merging**
