### PR TITLE
(maint) Add missing entries for Debian in metadata.json

### PR DESCRIPTION
**Pull request by smortex**
This module has support for all versions of Debian, but the
corresponding enty in metadata.json was missing.

### CODE REVIEW

**Comment by LukasAud** [comment]
Hi @smortex , we are currently working on this module looking to fixing some issues related with Debian. I noticed your PR here which might contain some helpful code. Could you let me know if this PR is still relevant and/or still a draft? Also, would you still be interested in working on it or can it be closed?

**Comment by smortex** [comment]
@LukasAud I forgot about this one: we are using at least the basic features of this module with great success on Debian, and I realized that it was lacking the metadata to say it worked so wanted to add it.  While I could fix a few issues in CI, I could not manage to fix all of them (I think the remaining failures where related to some kind of extensions I have no experience with).

Let's close and reopen this to re-trigger a CI build and have access to the failure logs which have expired :monocle_face: …

**Comment by smortex** [comment]
lol, this is way older than I though, and the code now disables Debian testing!

#1451 is probably a good start: the errors on Debian ring a bell, they are the ones I had.  The branch should be rebased on top of `main` to eliminate the merge commit and fixing can continue there.

I'll close this, thanks!

**Comment by LukasAud** [comment]
Hey @smortex. Yes, upon another inspection, it does look like this PR is a bit outdated, I'm glad we could close it now that it no longer serves a purpose. 

https://github.com/puppetlabs/puppetlabs-mysql/pull/1451 is the PR upon which the Puppet CAT (former IAC) team is currently working to resolve the Debian issues we are experiencing at a cloud level. It should be the latest available version of mySQL plus some minor code to re-enable Debian testing, so feel free to pull that code for any work you might be planning to do.

**Pull request closed without merging**
