### PR TITLE
Solaris/upstream

### PR DESCRIPTION
**Pull request by shawnferry**
(MODULES-4749) puppetlabs-mysql : Solaris support
(MODULES-5277) puppetlabs-mysql : default version fact is not set on Solaris
(MODULES-5495) puppetlabs-mysql : the OS formerly known as Solaris 12

This patch adds Solaris support as currently shipped by Oracle. Mysql
version is extracted from `pkg mediator mysql` and used to set path
values.

This patch also adds the structured fact mysql_solaris which holds
values for consumption in params.pp

Solaris 12 is now Solaris 11.4

(MODULES-5494) puppetlabs-mysql : default version for Solaris should be 5.7  

Mysql 5.5 has been EOLd and will be removed from Solaris. The new default version should be 5.7.  If mysql is installed or mediated that version will be used instead.

### CODE REVIEW

**Comment by shawnferry** [comment]
Restoring the path change in lib/puppet/provider/mysql_datadir/mysql.rb does not fix the spec failure

**Comment by shawnferry** [comment]
This appears to be failing due to things around [rspec-puppet-facts/pull/53](https://github.com/mcanevet/rspec-puppet-facts/pull/53)

**Comment by david22swan** [comment]
@shawnferry Is there any movement on this PR?

**Comment by shawnferry** [comment]
I'm looking at it now

**Comment by pmcmaw** [comment]
Hey @shawnferry,

Apologies but with this PR lying stale for so long I am going to close this. It needs a lot of work to get it rebased and up to date. If you disagree with my action please do not hesitate to reopen the PR and in advance apologize for my misjudgment.

I would like to reiterate how grateful we are as a team for your contribution. 

Many Thanks
The Modules Team

**Pull request closed without merging**
