### PR TITLE
Allow backupcompress for xtrabackup profile

### PR DESCRIPTION
**Pull request by Spuffnduff**
Since TNAJanssen's PR has been stale, I forked from his repo and am attempting to get it active again and hopefully merged in.

If there is anything missing or I need to do more, please let me know as I'm new to this.

### CODE REVIEW

**Comment by carabasdaniel** [comment]
Hi @Spuffnduff,

This looks good, but would it be possible to add some tests to verify that this is working as intended and maybe squash the commits ?

Once that's done I'll close https://github.com/puppetlabs/puppetlabs-mysql/pull/1154 and get this merged.

Thanks.

**Comment by Spuffnduff** [comment]
I'll look into squashing the commits. I may need some help in writing some tests but will reach out when the time comes.

**Comment by lionce** [comment]
Hello @Spuffnduff ,

Please let us know if we can help you! Thank you!

Cheers

**Comment by Spuffnduff** [comment]
I think I performed enough squash cleanup for this PR.  I noticed that there is a Travis test against this so it should rerun soon.  If not I will look into it.

**Comment by Spuffnduff** [comment]
Looking at the current .travis.yml file in my branch, it passes expect for Puppet v.4 which shouldn't matter. The current travis tests don't have that incorporated anymore (looking at the current master branch).

**Pull request merged**
