### PR TITLE
Set ordering of acceptance tests

### PR DESCRIPTION
**Pull request by ghoneycutt**
This allows pre_run to be removed from the spec_helper_acceptance as the
tests will run in a specific order. The pre_run just included the
mysql::server class which now happens first thing.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Based off of @pmcmaw 's previous work in trying to debug acceptance testing with Debian.

**Comment by daianamezdrea** [comment]
Hi @ghoneycutt, every acceptance test should be independent, if we merge this PR, we'll create dependencies between the tests, which we don't want. Thank you ! (https://softwareengineering.stackexchange.com/questions/46913/writing-acceptance-test-cases)

**Comment by ghoneycutt** [comment]
The acceptance tests already run in a specific order and when someone adds a new file that order will change. This only makes what is already happening explicit.

Also the tests are inherently dependent on each other because they are making changes to a system and checking the state of the system at that time. Unless you run each test block from the code on its own system in the same starting state, this will be the case and our testing frameworks (litmus and beaker) and processes in the community do not support that.

**Comment by ghoneycutt** [comment]
@daianamezdrea @pmcmaw Could you please have a look at this.

**Review by adrianiurca — APPROVED** [review]

**Comment by adrianiurca** [comment]
Hey @ghoneycutt, thank you for your contribution!

kind regards,
@adrianiurca

**Pull request merged**
