### PR TITLE
add mysql_native_password plugin to authentication_string vs password

### PR DESCRIPTION
**Pull request by Heidistein**
On a debian-11 server the plugin kept changing the password of a user. Turns out this user is using the plugin 'mysql_native_password', which does not use the PASSWORD field.

### CODE REVIEW

**Comment by Heidistein** [comment]
Those failing tests are not my failures, it is RPM dependency related

**Comment by daianamezdrea** [comment]
Hello @Heidistein, sorry for the late answer but our team went through some transformations, indeed the failures are not related with your PR, can you rebase it in order to have everything green and ready to merge? Thank you and sorry again

**Comment by Heidistein** [comment]
I have rebased the tree. Thanks

**Comment by daianamezdrea** [comment]
Hi @Heidistein, this looks good, the ubuntu errors are not related with your PR, thank you!

**Review by daianamezdrea — APPROVED** [review]

**Comment by Heidistein** [comment]
Thanks!

**Pull request merged**
