### PR TITLE
Added server_id fact

### PR DESCRIPTION
**Pull request by igalic**
use mac address for "guaranteed" uniqueness ;)

### CODE REVIEW

**Comment by igalic** [comment]
rebased, squashed and white-space clean version of #595.
tested (in production, obvs)

now the only thing left are rspec tests;)

**Comment by igalic** [comment]
@NoodlesNZ @dveeden comments?

**Comment by NoodlesNZ** [comment]
I'll write some rspec tests tomorrow for this if you want to hold off the merge.

**Comment by igalic** [comment]
+1

**Comment by igalic** [comment]
i'm in no hurry to merge it myself, as i've already merged it to my own mariadb branch ;)

**Comment by mhaskel** [comment]
@igalic this also needs docs in the README, the [Facts](https://github.com/puppetlabs/puppetlabs-apt#facts) section just doesn't exist yet since this is the first fact

**Comment by mhaskel** [comment]
Closes #595

**Comment by igalic** [comment]
aaaah. thanks. will add a doc!

**Comment by igalic** [comment]
done @mhaskel!

**Comment by igalic** [comment]
oh… tests… ~_~

**Comment by igalic** [comment]
tests *and* documentation. i'm on a roll today

**Comment by tphoney** [comment]
Really close :), i think it is a formatting issue.

**Comment by igalic** [comment]
missing an `it` block. because that makes perfect sense, rspec >_>

**Comment by igalic** [comment]
@mhaskel rebased and squashed, tests are still failing and i have absolutely no idea why.

**Comment by tphoney** [comment]
@mhaskel @igalic I may have committed some git shenanigans. But i found your problems, a couple of typo's macadddress should be macaddress. And fixing the comparison for lo. #686 is where i fixed it

**Pull request merged**
