### PR TITLE
Added server_id fact

### PR DESCRIPTION
**Pull request by NoodlesNZ**
A server_id fact for generating unique server_id's for replication.

### CODE REVIEW

**Comment by igalic** [comment]
@NoodlesNZ happy new year!

**Comment by NoodlesNZ** [comment]
A quick refactor. I've done a bit of testing, but will try it out on my dev servers tomorrow.

**Comment by dveeden** [comment]
@NoodlesNZ were you able to test it?

**Comment by mhaskel** [comment]
This was merged in #686

**Pull request closed without merging**
