### PR TITLE
parametrize xtradb package name

### PR DESCRIPTION
**Pull request by ndelic0**
This is a new pull request as the previous one could not be squashed before fixing the conflict.

### CODE REVIEW

**Comment by tphoney** [comment]
The travisci errors are known (working on them now), what PR was this based on @ndelic0 ?

**Comment by ndelic0** [comment]
https://github.com/puppetlabs/puppetlabs-mysql/pull/843

**Comment by ndelic0** [comment]
@tphoney travisci errors are gone.Hope this pull req is ok now?

**Comment by tphoney** [comment]
@ndelic0 you mentioned in the previous pull request, that you are making this change because of https://bugs.launchpad.net/percona-xtrabackup/+bug/1568049 and that you were going to set the package name like percona-xtrabackup-2{1..4} to specify version. In reality it is better to specify the version with https://docs.puppet.com/puppet/latest/reference/types/package.html#package-attribute-ensure. @DavidS any further comment ?

**Comment by ndelic0** [comment]
@tphoney I'm referring to name var here - package name : 
```
Available Packages
Name        : percona-xtrabackup
Arch        : x86_64
Version     : 2.3.4
Release     : 1.el6


Name        : percona-xtrabackup-21
Arch        : x86_64
Version     : 2.1.9
Release     : 746.rhel6

Name        : percona-xtrabackup-22
Arch        : x86_64
Version     : 2.2.13
Release     : 1.el6
```
I

**Comment by tphoney** [comment]
thanks for the further information

**Pull request merged**
