### PR TITLE
(MAINT) Removing EOL OS from metadata

### PR DESCRIPTION
**Pull request by Ramesh7**
## Summary

Removing EOL OS from metadata.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

### CODE REVIEW

**Review by bastelfreak — CHANGES_REQUESTED** [review]
please also remove the Code related to those OS versions

**Comment by Ramesh7** [comment]
> please also remove the Code related to those OS versions

First can you please confirm the list is correct or there are more OS which is already EOL?

**Comment by alexjfisher** [comment]
I know Voxpupuli's policy on this, but what is Puppet's? They still actively support EL7 in PE, don't they?

**Comment by Ramesh7** [comment]
> I know Voxpupuli's policy on this, but what is Puppet's? They still actively support EL7 in PE, don't they?

EL7 you mean CentOS 7? If yes then yes. Have observed that PE team is working on to the same to remove it.
Also as the CentOS 7 EOL was on 30th June, so releasing new module with major version so I think its needed step as well.
Open for thoughts.

**Pull request closed without merging**
